### ISSUE TITLE
Remote connections to Gremlin Server using "unknown" serializer

### ISSUE THREAD

**Issue by Will-Hardman** [davebshow/aiogremlin#12]
Hi Dave,

I've been integrating aiogremlin with the new Janusgraph 0.2 release and it works happily with TinkerPop 3.2.4.

On my development server I have been reading and writing over WebSockets with no problem at all.  The libray works beautifully.  However, when I attempt to read / write to the Gremlin Server from another machine I am hitting a problem and am not quite sure what to do about it.

Here's some sample code:

```
cluster = Cluster(loop=loop, hosts=[HOST_URL])
yield from cluster.open(loop=loop)
client = yield from cluster.connect()
result_set = yield from client.submit(message=query, bindings=bindings)
result = yield from result_set.all()
client.close()
```
The client establishes a connection fine, but the coro hangs at the `yield from result_set.all()` statement.

Checking the Gremlin Server logs I see the following:

```
70327197 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.server.handler.WsGremlinBinaryRequestDecoder  - Gremlin Server is not configured with a serializer for the requested mime type [application/vnd.gremlin-v3.0+json] - u
sing org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 by default
70327198 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV1d0  - Request [PooledUnsafeDirectByteBuf(ridx: 291, widx: 291, cap: 325)] could not be deserialized by org.apache.tinker
pop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV1d0.
70327198 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.server.handler.OpSelectorHandler  - Invalid OpProcessor requested [null]
```

It seems to me that aiogremlin is not using the expected serializer.  [http://aiogremlin.readthedocs.io/en/latest/usage.html](The aiogremlin docs) state that there is a kwarg called `message_serializer` for the `Cluster` object's `__init__` method, described as:

> String denoting the class used for message serialization, currently only supports basic GraphSONMessageSerializer

From my Googling this serializer is `org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0`, a.k.a. `application/vnd.gremlin-v1.0+json`, whereas aiogremlin appears to be serializing using `org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0`, a.k.a. `application/vnd.gremlin-v3.0+json`.

I tried changing my `gremlin-server.yaml` file to add the line:
`org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV3d0] }}` but this just results in the log message:

`Could not find configured serializer class - org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0 - it will not be available`

So I'm a little stumped.  Do you know what's going on?

**Comment by Will-Hardman** [comment]
And I've just resolved the issue.  I had foolishly left a command in my Docker script that was pip installing `gremlinpython`.  It was picking up the latest version which uses `GraphSONMessageSerializerV3d0` as the default serializer.  This is not supported by TP3.2.4 - which is what ships with Janusgraph 0.2.0.  For Janusgraph one needs `pip install gremlinpython==3.2.4 aiogremlin==3.2.4`.  And we're done :-)

**Comment by davebshow** [comment]
Hi @Will-Hardman I'm glad you figured this out. FYI, I think that Janus 0.2.0 is tested against TP 3.2.6 ([see here](https://github.com/JanusGraph/janusgraph/releases/tag/v0.2.0)). Therefore, I would recommend using gremlin-python 3.2.6:

```
$ pip install aiogremlin==3.2.6rc1
$ pip install gremlinpython==3.2.6 --no-deps
```
