### ISSUE TITLE
coroutine never awaited

### ISSUE THREAD

**Issue by xzy3** [davebshow/aiogremlin#15]
```
aiogremlin/driver/aiohttp/transport.py:22: RuntimeWarning: coroutine 'ClientWebSocketResponse.send_bytes' was never awaited
  self._ws.send_bytes(message)
```

I'm getting this warning while using goblin. It also seems that my db is not receiving the request. I added a return to that line and both problems went away.

aiogremlin 3.2.6
goblin 2.1.0

**Comment by davebshow** [comment]
It appears that `send_bytes` is now a coroutine (as of aiohttp 3.0), which means it should be awaited, not returned. We should probably use `asyncio.iscoroutine` to check now and await if necessary. Feel like doing a PR?

**Comment by xzy3** [comment]
done. I'm still learning the ropes of aio with python.
