### ISSUE TITLE
support latest aiohttp version (2.2.5)

### ISSUE THREAD

**Issue by takaomag** [davebshow/aiogremlin#6]
Hi,

Thank you for your nice module!
Current aiogremlin supports aiohttp==1.3.3. Is there any plan to support latest aiohttp version ?

I want to use new features of aiohttp.

**Comment by davebshow** [comment]
Yes, there will be a release shortly with TinkerPop 3.2.6 (end of next week I think). I will make sure to bump to the most recent version of `aiohttp`. Just curious, what are the new features you are interested in?

**Comment by takaomag** [comment]
Thanks.

Regarding graph traversal and manipulation, I don't care about underlying aiohttp version. No problem.

But I want to use aiohttp for the other purposes in same process (ex. gunicorn http server or http client with asyncio loop).

**Comment by davebshow** [comment]
Hi @takaomag sorry for the delay. Version 3.2.6rc1 supports aiohttp 2.2.5.

**Comment by takaomag** [comment]
Thanks! I will try it.
