### ISSUE TITLE
Misleading version

### ISSUE THREAD

**Issue by trojek** [davebshow/aiogremlin#8]
In docs one can read: `pip install gremlinpython==3.2.6 --no-deps` but the currenct version of aiogremlin is 3.2.6rc1.
In the goblin project, TravisCI informs that there is a problem with a build which is strictly connected with aiogremlin version.

**Comment by davebshow** [comment]
Yeah the goblin build has been hosed for a while, I will be getting to that soon. Otherwise, I'm not sure what the problem is. gremlinpython 3.2.6 is the one you want for the aiogremlin 3.2.6rc1

**Comment by trojek** [comment]
You are right. I was confused about aiogremlin version and gremlin dependency, not gremlinpython.
