### ISSUE TITLE
docs: incomplete objects.inv for intersphinx

### ISSUE THREAD

**Issue by jirikuncar** [davebshow/aiogremlin#9]
Published `objects.inv` on Read the Docs does not contain all references used by Goblin.

**Comment by davebshow** [comment]
Not sure what is up with this one exactly. I fixed the readthedocs build for this library. I can build goblin locally but it is still failing to generate API docs on rtd

**Comment by jirikuncar** [comment]
I usually try to run `sphinx-build` with `-W` option to catch missing references.

**Comment by davebshow** [comment]
I can't seem to find any missing references. I don't get any warnings, and therefore no errors with -W, can you shed some light on this?

**Comment by jirikuncar** [comment]
I will send a PR which adds all missing references from `gremlin`. Update: It looks like you have already fixed some of the broken RTD builds.
